version: "3"
services:
  mariadb:
    image: mariadb:latest
    container_name: number8db
    ports:
      - 3306:3306
    environment:
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASS}
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MARIADB_DATABASE=${DB_NAME}
    volumes:
      - ./dbs/backup:/home/backup
      - ./dbs/backup/backup.sql:/docker-entrypoint-initdb.d/backup.sql
